"use client";

import { MiniKit } from "@worldcoin/minikit-js";
import { useWaitForTransactionReceipt } from "@worldcoin/minikit-react";
import { useState } from "react";
import { type Address, createPublicClient, http } from "viem";
import { worldchain } from "viem/chains";
import { Button } from "@/components/ui/button";
import { IMPOSSIBLE_ADDRESS } from "@/lib/constants";
import { impossibleAbi } from "@/lib/contracts/abi";
import { env } from "@/lib/env";

// Create a public client for Worldchain
const client = createPublicClient({
  chain: worldchain,
  transport: http(""),
});

export default function DemoTxPage() {
  const [transactionId, setTransactionId] = useState<string>("");
  const [error, setError] = useState<string | null>(null);

  // Wait for transaction confirmation
  const { isLoading: isConfirming, isSuccess: isConfirmed } =
    useWaitForTransactionReceipt({
      client,
      appConfig: {
        app_id: env.NEXT_PUBLIC_WORLD_APP_ID,
      },
      transactionId,
    });

  const sendTransaction = async () => {
    try {
      setError(null);
      setTransactionId("");

      // TODO: Change these values to the actual values
      const tournamentId = BigInt(1); // Tournament ID
      const amount = BigInt("1000000000000000000"); //Amount to claim in wei
      const proof: `0x${string}`[] = ["0x01"] as `0x${string}`[]; // Proof generated by the generate-claim-proof API route

      const { finalPayload } = await MiniKit.commandsAsync.sendTransaction({
        transaction: [
          {
            address: IMPOSSIBLE_ADDRESS as Address,
            abi: impossibleAbi,
            functionName: "claimPrize",
            args: [tournamentId, amount, proof],
          },
        ],
      });

      if (finalPayload.status === "error") {
        console.error("Error sending transaction", finalPayload);
        setError(
          `Transaction failed: ${finalPayload.error_code || "Unknown error"}`
        );
      } else {
        setTransactionId(finalPayload.transaction_id);
      }
    } catch (err) {
      console.error("Error in sendTransaction:", err);
      setError(
        err instanceof Error ? err.message : "Failed to send transaction"
      );
    }
  };

  return (
    <div className="flex min-h-screen flex-col items-center justify-center gap-6 p-8">
      <div className="w-full max-w-md space-y-6 rounded-lg border border-gray-800 bg-gray-900/50 p-6">
        <div className="space-y-2">
          <h1 className="font-bold text-2xl">Demo Transaction</h1>
          <p className="text-gray-400 text-sm">
            Example of sending a claimPrize transaction using Worldcoin Miniapp
            SDK
          </p>
        </div>

        <div className="space-y-4 rounded-md bg-gray-800/50 p-4">
          <div className="space-y-1">
            <p className="font-semibold text-gray-400 text-xs">Function:</p>
            <p className="font-mono text-sm">claimPrize</p>
          </div>
          <div className="space-y-1">
            <p className="font-semibold text-gray-400 text-xs">
              Hardcoded Values:
            </p>
            <div className="space-y-1 font-mono text-gray-300 text-xs">
              <p>tournamentId: 1</p>
              <p>amount: 1000000000000000000 (1 token)</p>
              <p>proof: [0x01, 0x02, 0x03]</p>
            </div>
          </div>
        </div>

        <Button
          className="w-full"
          disabled={isConfirming || isConfirmed}
          onClick={sendTransaction}
        >
          {isConfirming
            ? "Confirming Transaction..."
            : isConfirmed
              ? "Transaction Confirmed!"
              : "Send Transaction"}
        </Button>

        {transactionId && (
          <div className="space-y-2 rounded-md bg-blue-900/20 p-4">
            <p className="font-semibold text-blue-400 text-xs">
              Transaction ID:
            </p>
            <p className="break-all font-mono text-blue-300 text-xs">
              {transactionId}
            </p>
          </div>
        )}

        {isConfirming && (
          <div className="rounded-md bg-yellow-900/20 p-4">
            <p className="text-sm text-yellow-400">
              ⏳ Waiting for transaction confirmation...
            </p>
          </div>
        )}

        {isConfirmed && (
          <div className="rounded-md bg-green-900/20 p-4">
            <p className="text-green-400 text-sm">
              ✅ Transaction confirmed successfully!
            </p>
          </div>
        )}

        {error && (
          <div className="rounded-md bg-red-900/20 p-4">
            <p className="text-red-400 text-sm">❌ Error: {error}</p>
          </div>
        )}
      </div>
    </div>
  );
}
